title: "Philip Foster's Professional Portfolio"
description: "Philip Foster's personal site and blog."
baseurl: "" # Keep empty unless your site is in a subdirectory
url: "https://pipfoster.uk" # Your custom domain

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude the _site folder and other unnecessary files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _site
